### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by trickypr** [pulse-browser/experiment#37]
> [!NOTE]
> I have no plans to implement depreciated APIs unless they assist a browser feature

- [ ] Properties
  - [ ] `tabs.TAB_ID_NONE`
- [ ] Functions
  - [ ]  `tabs.captureTab()`
  - [ ] `tabs.captureVisibleTab()`
  - [ ] `tabs.connect()`
  - [ ] `tabs.create()`
  - [ ] `tabs.detectLanguage()`
  - [ ] `tabs.discard()`
  - [ ] `tabs.duplicate()`
  - [ ] `tabs.executeScript()`
  - [x] `tabs.get()` - Impl #57 
  - [ ] `tabs.getCurrent()`
  - [ ] `tabs.getZoom()` - Dep #9 
  - [ ] `tabs.getZoomSettings()` - Dep #9
  - [x] `tabs.goForward()` - Impl #57
  - [x] `tabs.goBack()` - Impl #57 
  - [ ] `tabs.hide()` - Dep #47
  - [ ] `tabs.highlight()`
  - [ ] `tabs.insertCSS()`
  - [ ] `tabs.move()`
  - [ ] `tabs.moveInSuccession()`
  - [ ] `tabs.print()` - Dep #48
  - [ ] `tabs.printPreview()` - Dep #48
  - [x] `tabs.query()` - Impl #57
  - [x] `tabs.reload()` - Impl #57
  - [x] `tabs.remove()` - Impl #57 
  - [ ] `tabs.removeCSS()`
  - [ ] `tabs.saveAsPDF()` - Dep #48?
  - [ ] `tabs.sendMessage()`
  - [ ] `tabs.setZoom` - Dep #9 
  - [ ] `tabs.show()` - Dep #47
  - [ ] `tabs.toggleReaderMode()`
  - [x] `tabs.update()` - Impl #57 
  - [ ] `tabs.warmup()`
- [ ] Events
  - [ ] `tabs.onActivated`
  - [ ] `tabs.onAttached`
  - [ ] `tabs.onCreated`
  - [ ] `tabs.onDetached`
  - [ ] `tabs.onHighlight`
  - [ ] `tabs.onMoved`
  - [ ] `tabs.onRemoved`
  - [ ] `tabs.onReplaced`
  - [ ] `tabs.onUpdated`
  - [ ] `tabs.onZoomChange` - Dep #9

**Comment by trickypr** [comment]
Reference documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs
Mozilla's schema (under chromium's license): https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/tabs.json
This will have to be implemented in batches
