### ISSUE TITLE
Multiwindow

### ISSUE THREAD

**Issue by trickypr** [pulse-browser/experiment#5]
- [x] Add option to hamburger menu
- [x] Context menu option
- [x] Drag tabs between windows
- [x] Drag onto separate screen for new window
- [x] (Optional?) Implement some equivalent to [BrowserWindowTracker.sys.mjs](https://searchfox.org/mozilla-central/source/browser/modules/BrowserWindowTracker.sys.mjs)
- [x] Tab drag should have the website image
- [x] New window keyboard shortcut
