### ISSUE TITLE
Global Context Menu

### ISSUE THREAD

**Issue by trickypr** [pulse-browser/experiment#7]
- [ ] Context Menu Items
  - [x] Navigation (back, forward, reload)
  - [x] Bookmark
  - [ ] Spellcheck options (#4)
  - [x] Open in new window (#5)
  - [ ] Bookmark link
  - [ ] Save link as
  - [ ] Media controls (Play, Pause, Mute, Speed, etc)
  - [x] Open image in new tab
  - [x] Save image as
  - [x] Copy image
  - [x] Copy image link
  - [ ] PDFJS context items
  - [ ] Iframe options
    - [ ] Open in tab
    - [ ] Open in window
    - [ ] Reload
    - [ ] Bookmark
    - [ ] Save
    - [ ] View source
  - [ ] View page source
  - [ ] Open inspector (#6)
- [x] Customizable context menu (#8)
- [ ] Tillable / Icon grid actions

**Comment by trickypr** [comment]
Quick mockup for what customization might look like: https://svelte.dev/repl/c34f6d83ee9a413d9d3885a3b021a8a8?version=4.2.3
